baseURL = 'https://www.wellfleet4palestine.org/'
languageCode = 'en-us'
title = 'Wellfleet for Palestine'
theme = "hugo-universal-theme"
themesDir = "themes"
# theme = 'ananke'

# Define the number of posts per page
pagination.pagerSize = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
name       = "Home"
identifier = "menu.home"
url        = "/"
weight     = 1

[[menu.main]]
name       = "About"
identifier = "menu.about"
url        = "/about/"
weight     = 2

[[menu.main]]
name       = "Actions"
identifier = "menu.actions"
url        = "/actions/"
weight     = 3

[[menu.main]]
name       = "Films"
identifier = "menu.films"
url        = "/palestine-film-series/"
weight     = 4

[[menu.main]]
name       = "Farmers Market"
identifier = "menu.market"
url        = "/farmers-market/"
weight     = 5

[[menu.main]]
name       = "News"
identifier = "menu.news"
url        = "/news/"
weight     = 6

[[menu.main]]
name       = "The Arts"
identifier = "menu.arts"
url        = "/arts/"
weight     = 7

[[menu.main]]
name       = "Calendar"
identifier = "menu.calendar"
url        = "/calendar/"
weight     = 8

[[menu.main]]
name       = "Contact"
identifier = "menu.contact"
url        = "/contact/"
weight     = 9

# Top bar social links menu

[[menu.topbar]]
weight = 1
name = "Phone"
url = "tel:+1 415-935-3581"
pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
weight = 2
name = "Instagram"
url = "https://www.instagram.com/wellfleet4palestine/"
pre = "<i class='fab fa-2x fa-instagram'></i>"

#[[menu.topbar]]
#weight = 3
#name = "Facebook"
#url = "http://facebook.com"
#pre = "<i class='fab fa-2x fa-facebook'></i>"

#[[menu.topbar]]
#weight = 4
#name = "Twitter"
#url = "http://twitter.com"
#pre = "<i class='fab fa-2x fa-twitter'></i>"

#[[menu.topbar]]
#weight = 5
#name = "Email"
#url = "mailto:info@wellfleetsoftware.com"
#pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
viewMorePostLink = "/blog/"
author = "Wellfleet for Palestine"
defaultKeywords = ["wellfleet", "Palestine"]
mainSections = ["blog"]
defaultDescription = "Wellfleet for Palestine Website"

# Social media
facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
instagram_site = "https://www.instagram.com/wellfleet4palestine/"
default_sharing_image = "images/sharing-default.png"

# Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
enableGoogleMaps = false
googleMapsApiKey = "PLACEHOLDER"

latitude = "41.9305"
longitude = "70.0310"

#Â Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
style = "palestine"

about_us = "Wellfleet for Palestine ðŸ‡µðŸ‡¸ (W4P) is a group of Wellfleet residents who are committed to freedom, equality and justice for Palestinians."

copyright = "Copyright (c) 2023 - 2025, Wellfleet for Palestine; all rights reserved."

# Format dates with Go's time formatting
date_format = "January 2, 2006"

dropdown_mouse_over = false

disabled_logo = false
logo_text = "Wellfleet for Palestine"

logo = "images/w4p-logo-banner.png"
logo_small = "images/w4p-logo-banner.png"
contact_url = "/contact"
#address = """<p class="text-uppercase"><strong>Wellfleet Software</strong>
#        <br>150 Old Chequessett Neck Road
#        <br>Wellfleet, MA 02667
#        <br>
#        <strong>United States of America</strong>
#      </p>
#      """

#[permalinks]
#    blog = "/blog/:year/:month/:day/:contentbasename/"

# Enable or disable top bar with social icons
[params.topbar]
enable = true
text = """<p class="hidden-sm hidden-xs">ðŸ‡µðŸ‡¸ Contact us on wellfleet4palestine@gmail.com. Follow us on instagram.ðŸ‡µðŸ‡¸</p>
      <p class="hidden-md hidden-lg"><a href="tel:+1 415-935-3581" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:wellfleet4palestine@gmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
search = false
categories = false
tags = false

[params.carouselCustomers]
items = 6
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.carouselTestimonials]
items = 4
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.carouselHomepage]
# All carousel items are defined in their own files. You can find example items
# at 'exampleSite/data/carousel'.
# For more information take a look at the README.
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.features]
enable = false
cols = 3 # Default: 3, Available values 2,3,4,6
# All features are defined in their own files. You can find example items
# at 'exampleSite/data/features'.
# For more information take a look at the README.

[params.testimonials]
enable = false
# All testimonials are defined in their own files. You can find example items
# at 'exampleSite/data/testimonials'.
# For more information take a look at the README.
title = "Testimonials"
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
enable = false
icon = "far fa-file-alt"
title = "Do you want to see more?"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
link_url = "#"
link_text = "Check other homepages"

[params.clients]
enable = false
# All clients are defined in their own files. You can find example items
# at 'exampleSite/data/clients'.
# For more information take a look at the README.
title = "Our Clients"
subtitle = ""

[params.recent_posts]
enable = false
title = "From our blog"
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
hide_summary = false

[params.footer.recent_posts]
enable = false

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
[markup.goldmark.parser.attribute]
block = false
title = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "w4p-website"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://www.wellfleet4palestine.org/"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://<Bucket Name>?region=<AWS region>"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
#cloudFrontDistributionID = <ID>

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# See https://golang.org/pkg/regexp/syntax/ for pattern syntax.
# Pattern searching is stopped on first match.

# Samples:

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

